### PR TITLE
Mini Game.

### PR DESCRIPTION
**Pull request by jammln**
The game is based on flappy birds and currently randomly generates the level with different spaces between pillars and different pillar heights. The collision detection isn't perfect and could do with some improvement. There are some basic menu screens so the player knows the controls and if they win or loose. The game is capped to 30 fps and runs quite smoothly on an Intel I3.
I hope you enjoy playing it!

### CODE REVIEW

**Comment by maximecb** [comment]
Very cool, thank you for making this.

I love the text rendering and might reuse it for other purposes :)

If you have time for improvements, it would be nice to see more explanative comments, and the currently commented-out bits of code removed, etc. Since this is under /examples, it can serve to help people get started with ZetaVM.

**Comment by maximecb** [comment]
@jammln I did notice one minor bug: one column of pixels at the left of the screen remains blue after the first pillar passes through.

I also think the game needs to allow space or enter to restart when you die.

**Comment by jammln** [comment]
Yeah, I noticed that bug too but I was too tired to get my head around it. I knows it to do with the scrolling of the pillars. I'll try to clean up the code to make it more obvious what is going on. The text worked a lot better than I expected.

**Comment by krypt-n** [comment]
If I understand the code correctly, `pxx` is the column right after a pillar. Consider the case `px < 0 && pxx == 1`, then the rectangle from 1 to 2 is cleared and a new rectangle is drawn from 0 to 1, in the next iteration `px < 0 && pxx == 0`. In this case the rectangle from 1 to 1 is cleared and a new rectangle is drawn from 0 to 0. (Nothing is cleared and nothing is drawn, since start == end, thus the column 0 is never cleared.

**Comment by jammln** [comment]
Yeah, that is the bug. I wrote some corner case code for that situation which fixes it. Thanks for the help.

**Pull request merged**
