### PR TITLE
Initial implementation of std/array

### PR DESCRIPTION
**Pull request by ashwanidausodia**

### CODE REVIEW

**Comment by Maaarcocr** [comment]
Good start! 
Do we think that we should have a type check at the start of every function so that we are sure that the parameters passed to the function are of the right type?

**Comment by ashwanidausodia** [comment]
@Maaarcocr Type checking should be done in vm not in standard lib.

**Comment by Maaarcocr** [comment]
@ashwanidausodia I was suggesting to have something like an assert statement at the beginning of the functions, so that we can have nicer error messages. 
For example an object in plush could have a length field and objects support the getElem operator (object[key]), so for example the map function would fail saying that a field is missing (I think).

**Comment by ashwanidausodia** [comment]
@Maaarcocr I agree that you can get nicer error messages by adding some type checks. But I believe that error messages in vm and plush will improve over time and then these type checks will become redundant. Remember type checks come with a runtime cost.

**Comment by Maaarcocr** [comment]
I think that in case, especially for functions like map, it's really difficult to make them any better. The VM is already typed, so it's up to the language implementers to use the right ops. 
If the way we get props and get elems in plush will not change, improvements will be difficult to accomplish. 
I think that the main focus of BBV ( @maximecb probably know better than me ) is to reduce runtime costs on type checking, thus I don't think that in the long run we will have a huge impact on performance due to this.

**Comment by maximecb** [comment]
@ashwanidausodia Very good work. I saw you even thought to include `filter`. Will merge what you have so far. @krypt-n has made some good suggestions on other additions in #78.

@Maaarcocr is right that the messages can be made more specific if we do type assertions in the array functions. However, if you do add type checks, you should throw exceptions. The `assert` statement is meant for parts of programs that can't be reached in normal circumstances. BBV should (eventually) be able to eliminate most type checks, so there should be no overhead in adding extra sanity checks here and there.

**Pull request merged**
