### PR TITLE
Added binarySearch and contains function for arrays.

### PR DESCRIPTION
**Pull request by jammln**
I have added tests for both functions and they pass. I do have some concerns with the binary search implementation which I have commented within the code.

I hope this helps with the development of both Zeta and Plush.

### CODE REVIEW

**Comment by krypt-n** [comment]
There is a new `idiv` function in the math package that handles integer division. Otherwise the functions are looking good to me.

All functions that search for something and return an index currently return `-1` if the element is not in the string/array.

**Comment by maximecb** [comment]
I second with @krypt-n's comments.

Nitpick: you used tabs instead of 4 spaces as we are currently doing (I need to get around to writing a coding style guide).

**Comment by jammln** [comment]
@krypt-n "All functions that search for something and return an index currently return -1 if the element is not in the string/array." The binary search returns the actual item within the array instead should I return the index where the item was found instead then?

**Comment by krypt-n** [comment]
@jammln Ah, completely missed that. If you return the element -1 is probably not usable an an error code since it might be the element the user was searching for. For consistency it would be nice to return the index. Both or probably not very useful to the caller right now, since the comparisons only work on integers and floats.

**Comment by maximecb** [comment]
:+1:

**Pull request merged**
