### PR TITLE
Fix 3 problems on 32bit targets

### LINKED ISSUE #116: Core dump seen on 32 bit machine
Assertion seen while running `Zeta` 
Below is the stack trace for `./zeta  --test`
```
(gdb) r --test
Breakpoint 2, testRuntime () at vm/runtime.cpp:763
763 {
(gdb)
764 std::cout << "runtime tests" << std::endl;
(gdb)
764 std::cout << "runtime tests" << std::endl;
(gdb)
runtime tests
789 assert (arr.getElem(0) == Value::ZERO);
(gdb)
792 auto arr2 = Array(0);
(gdb)
793 assert (arr2.length() == 0);
(gdb)
794 arr2.push(Value::ONE);
(gdb)
zeta: vm/runtime.cpp:120: uint8_t* Wrapper::getNextPtr(refptr, refptr): Assertion `nextPtr != nullptr' failed.
Program received signal SIGABRT, Aborted.
0xb7fdd428 in __kernel_vsyscall ()
(gdb) p Value::ONE
$1 = {word = {float32 = 1.40129846e-45, int64 = 1, int32 = 1, int8 = 1 '\001', ptr = 0x1 <error: Cannot access memory at address 0x1>},
tag = 2 '\002', static ZERO = {word = {float32 = 0, int64 = 0, int32 = 0, int8 = 0 '\000', ptr = 0x0}, tag = 2 '\002',
```

Machine and compiler details are below
```
universe@universe-Lenovo-G50-80:~/zetavm$ uname -a
Linux universe-Lenovo-G50-80 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:56:31 UTC 2017 i686 i686 i686 GNU/Linux
universe@universe-Lenovo-G50-80:~/zetavm$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
```

### PR DESCRIPTION
**Pull request by krypt-n**
There were assumptions that `sizeof(uint64_t) == sizeof(intptr_t) == sizeof(refptr)` in the code, which lead to the problems described in #116 .

Fixes #116 

`make test` now succeeds on my machine with `-m32` and without.

### CODE REVIEW

**Comment by noundlas** [comment]
Is regex stuff also fixed with this??

**Comment by krypt-n** [comment]
Yeah true. It won't matter right now, since all we do is check a single bit but we might run into issues later. I'll change it into a `uintptr_t`.

**Comment by maximecb** [comment]
Good work finding these bugs :)

One comment:

`typedef uintptr_t obj_header`

Also, do you think you could modify the travis config so that it tests -m32? (on linux only).

**Comment by maximecb** [comment]
@krypt-n It did not quite work :O

**Comment by maximecb** [comment]
@krypt-n We need you! :octocat:

**Comment by krypt-n** [comment]
Alright, CI "works" now, using a sketchy docker image though.

**Comment by maximecb** [comment]
@krypt-n Thanks for getting back to this.

It looks good to me. Why do you say the docker image is sketchy? Anything we can address?

**Pull request merged**
