### PR TITLE
Add and export get_local_time to core/time/0

### PR DESCRIPTION
**Pull request by bigs**
Addresses #103. I've got the flu and these little issues are helping pass the time!

No tests written, though I've verified the functionality myself. Worth writing a test for? Furthermore, it _seems_ as though this library should be present on Windows, though I can't verify that for myself at the moment.

### CODE REVIEW

**Comment by maximecb** [comment]
It's nice to have your help @bigs.

Yes, I do think it's worth having tests. Should minimally check that you can call the `get_local_time` function, and that valid numbers are produced (eg: minutes is between 0 and 59).

I don't have a windows machine either, but AppVeyor builds and tests zeta on windows when you submit a PR. I relied on that to check that the performance counter code compiles.

**Comment by bigs** [comment]
tests implemented, branch squashed with a decent commit message. appears to run on appveyor, too.

**Comment by maximecb** [comment]
Nice. Just a small detail but, could you make `is_dst` a boolean value instead of `int32`?

**Comment by bigs** [comment]
@maximecb that caught my eye as well. the docs state that 0 = false, > 0 true, < 0 inconclusive. so i think the proper encoding is `Maybe Bool` which is why i left it as an integer. thoughts?

**Comment by maximecb** [comment]
Ho boy. It seems some time zones don't have dst, and I guess it's possible the local system could simply not know if the date is dst or not. I guess we have no choice but to expose that weird quirk.

A dynamic language way to do `Maybe Bool` could be to have `true`, `false` booleans, and `undef` when it's not set. It's not as nice as the `Maybe` type because it can't force you to check if it's defined or not.

**Comment by bigs** [comment]
haha yeah. i'd thought about the undefined approach and would be happy to take it, perhaps adding in some documentation.

**Comment by maximecb** [comment]
Some documentation in the comments would be sufficient.

**Comment by bigs** [comment]
just to clarify: take the undef approach and add some documentation? or keep the int representation and document it?

**Comment by maximecb** [comment]
Undef approach + doc please :+1:

**Comment by maximecb** [comment]
No problem. Sorry it took so much back and forth for something so simple, lol.

**Comment by bigs** [comment]
lol async communication has its ups and downs. on to the next!

**Pull request merged**
