### PR TITLE
Add bitwise operators.

### PR DESCRIPTION
**Pull request by tommyettinger**
I figured I will need this for #39 , so I might as well try to get this working. It passes all tests locally.

I'm not sure how complete this is, or if there's some untested mode that I wouldn't be aware of a regression in, because benchmarks/plush_parser.pls  didn't have several important operators that plush/parser.pls already had, and I did not add the bitwise operators to that file in benchmarks/. Other than that, C++ and Plush files have been added to, and the only change that may be an issue is line 1119 (previously 1113) of plush/parser.pls, where it was necessary to reduce the amount of precedence difference. The case that precipitated this was that `||` would be parsed as `|` followed by `|` if that operator was in the RHS of another `||` call, as with `a || b || c`. Allowing the same precedence level (which is always higher than 0, because no operators have 0 precedence) means `||` can be used with other `||` operations without issue. This may have surfaced anyway if an operator like `|>` was introduced and could be chained, since that might be parsed as `|` with precedence 5 followed by `>` with precedence 9.

### CODE REVIEW

**Comment by maximecb** [comment]
Overall, very well-done. This is indeed a feature that the VM lacked 👍  :)

A few comments:

1. You don't need to change the parser benchmark. I would prefer you revert the changes to it.

2. For the bitwise negation operator, this is not valid:

```
+            // Generate -1 - x
 +            ctx:addPush(-1);
 +            genExpr(ctx, expr.expr);
 +            runtimeCall(ctx, rt_sub);
```

The problem here is that people may try to apply ~x to floating-point values, and we want the result of that to be an error, not 1 - x.

3. Since you changed the parsing wrt operator precedence, can you add a few expression tests to tests/plush/simple_exprs.pls. Would like to make sure that things like `2 * 3 + 1` correctly accounting for operator precedence.

**Comment by tommyettinger** [comment]
OK, I implemented your recommendations. I believe the current plush_parser.pls file is identical to the one from before my changes, with the only possible change being a final newline that I can't tell if it was there or not in earlier versions. There's already an rt_not so I added rt_bit_not, which checks that its argument is a 32-bit int and uses the C `~` operator internally. Operator precedence is checked a good deal in simple_exprs.pls .

When I was considering tests to write in simple_exprs.pls, I noticed that there's no integer division operator, and even though it's reasonable enough to divide two ints, get a float back, and cast or otherwise convert the float to an int, that seems like it's more work than desirable. Would an operator specifically for truncating (and maybe also rounding) integer division make sense?

**Comment by maximecb** [comment]
Very good. I would prefer that the bitwise operators accept only integers, no booleans, however. My general mentality when it comes to the design of Zeta and Plush is that it's better to be strict. We can always remove restrictions later on, but adding restrictions is difficult. If we allow bitwise ops on booleans, then people will start using | and & for logical ops everywhere.

WRT division. That is a good idea, let's make it a separate pull request. We could have an integer division operator which maps to DIV_I32 and accepts only integers. Not sure what the symbol for that should be, maybe `x !/ y`.

**Comment by werediver** [comment]
In Pascal there are `div` and `/` operators, for integer and real division respectively. If there is no restrictions on the character set for an operator name, this could be an option.

**Comment by maximecb** [comment]
There is no restriction on the operator characters.

**Comment by tommyettinger** [comment]
I think the bitwise-and-logic-type operators should be usable with booleans as well as ints, though not with mixed boolean and int arguments. Most languages I can think of with both `|` and `||` operators (as well as `&` and `&&`) allow both bitwise and logical OR and AND on booleans, because they have different short-circuit and assignment-combining qualities. Where I can recall specifics, `||` usually short-circuits evaluation once a true value is found (which I think it also does in Plush), while `|` does not and always evaluates both sides (I'm pretty sure my PR matches this behavior). One argument to `|` or `||` might be a function call with side effects, so the short-circuit evaluation rule can be relevant. Also, I use `^=` not-infrequently on booleans, since the alternative to `x ^= y;` is `x = (x != y);`, which isn't concise but could sometimes be clearer. I believe I have used `|=` with booleans as well, and I know I have with integers. It isn't common, for sure, but it's good to have a wider range of options for handling short-circuit evaluation when it isn't always correct.

**Comment by maximecb** [comment]
I much prefer the stricter semantics.

**Comment by tommyettinger** [comment]
OK, so would there be a logical other operator/function for eager evaluating or/and ? Any user-defined function would do that just because of how functions evaluate, I guess... I'll commit the int-only bitwise or/and/xor and keep an eye out for reasonable ways to specify this when I start the int-only division commit; it might make sense for certain prefixes on operators to mean they perform strict type checks for one type in particular, and in the case of division, can have different output types than normal less-strict operators (since `/` can be used on both ints and floats, but always produces floats).

**Pull request merged**
