### PR TITLE
String lib

### PR DESCRIPTION
**Pull request by krypt-n**
This is my current progress on the string library proposed in #73. I'm opening a PR so that people can give feedback and leave remarks.

The first version will have no UTF-8 support, since that will be substantially more effort than a few spare hours here and there. Also note that zetavm currently uses signed chars, which could make working with byte values a bit weird in the future.

Implemented functions:

* [x] toString
* [x] indexOf
* [x] substring /slice
* [x] split
* [x] join
* [x] ord/char: These directly use zeta opcodes, is that okay for a library or should they be moved to a language runtime?
* [x] toLower, toUpper
* [x] trim
* [x] replace
* [x] format
* [x] intToString: inverse of parseInt, i.e. supports different radices
* [x] parseInt
* [x] startsWith
* [x] isWhitespace

What would be the best way to include documentation for these functions?

### CODE REVIEW

**Comment by maximecb** [comment]
Great :)

> note that zetavm currently uses signed chars, which could make working with byte values a bit weird in the future.

You mean that char values are in the -128 to 127 range? If so, that seems like a bug. I can fix that and make the char access functions produce values in 0, 255 instead.

Feedback:

- I would rather the names be camelCase, eg: `exports.tostring` => `exports.toString`

- Some names could be more descriptive, eg: `exports.char` => `exports.intToChar`, or `fromCharCode` as in JS.

- Would be good to comment on the purpose of functions such as `bm_makeoffsettable`

- I don't understand why the `1 == 2` in `assert(format("{}, {} and {}", ["numbers", 1, 2, 1 == 2]) == "numbers, 1 and 2");`

**Comment by krypt-n** [comment]
> You mean that char values are in the -128 to 127 range? If so, that seems like a bug. I can fix that and make the char access functions produce values in 0, 255 instead.

Correct

> Some names could be more descriptive, eg: exports.char => exports.intToChar, or fromCharCode as in JS.

python and some other languages use `ord` and `chr`. But they are probably not gonna be used often in not-library code, so no reason to save some keystrokes here.

> I don't understand why the 1 == 2 in assert(format("{}, {} and {}", ["numbers", 1, 2, 1 == 2]) == "numbers, 1 and 2");

Left over from an earlier test and I didnt notice it since format doesn't check the array length.

**Comment by maximecb** [comment]
This commit should fix the signed char issue: https://github.com/zetavm/zetavm/commit/ef3a21ccbfe0ab8ce89ec1843d15a979e2cbd0f0

Thanks for pointing that out.

**Comment by maximecb** [comment]
@krypt-n How are things? Hit any issues?

**Comment by maximecb** [comment]
> What would be the best way to include documentation for these functions?

I've been going with Javadoc-style comments above functions:

```
/**
Produce a string representation of an integer of a given radix.
*/
exports.intToString = function (val, radix)
{
   ...
}
```

Some feedback:

- Good work on the tests. It's good that you've added multiple test cases for functions.

- `intToString`: I wouldn't add the '0x' or '0b' prefixes. Let people add those themselves if they need them for their purpose.

- I would keep the helper functions that aren't exported separate from the exported functions.

- `toString`: for objects, you should call obj:toString()

- I added `math.idiv(x, y)` for integer division. Could also add an `x _/ y ` operator if you like.

Very happy to see this taking shape. It fills a huge functionality gap in the Zeta ecosystem :)

**Comment by maximecb** [comment]
@krypt-n I think you could also export isWhitespace as exports.isSpace(ch). It may be useful to people.

**Comment by krypt-n** [comment]
Alright, "done". Should I squash the commits?

**Comment by maximecb** [comment]
Very nice! Sure, squashing the commits would make sense.

**Pull request merged**
