### PR TITLE
Extend math library support for pow, log, exp

### PR DESCRIPTION
**Pull request by bigs**
This is a work in progress, extending the math library to support pow, log, and exp operations. 

Addresses #113

### CODE REVIEW

**Comment by Maaarcocr** [comment]
@bigs super small nitpick: this solves #113 😄

**Comment by bigs** [comment]
@Maaarcocr LOL recursive PR!

**Comment by maximecb** [comment]
@bigs At the moment you're calling exp instead of pow?

**Comment by bigs** [comment]
clearly this was pre coffee omg. will finish up tonight. want me to do i this coercing as demonstrated in other parts of stdlib?

**Comment by maximecb** [comment]
@bigs You're missing a break statement after the POW_F32 case in the switch.

**Comment by bigs** [comment]
int coercing*. yeah i’ll get that cleaned up and finish implementation w safety checks tonight 👍🏻

**Comment by maximecb** [comment]
Wrt int coercing, you mean `$i32_to_f32` ? I think that's currently the only way we have to convert int and float.

**Comment by bigs** [comment]
@maximecb pushed up a few changes... still likely a WIP (needs some tests at the very least.) made a decision re: `exp` which i'm happy to reverse (undefined if it overflows essentially) but figured this would be a decent point to check in. feel free to take the reigns to finish it off if you feel it's close and don't wanna do the back and forth. otherwise i'm happy to chew on it til it's done.

**Comment by maximecb** [comment]
If you have time tonight, what's missing is more tests and some error checking for invalid inputs.

I also think you don't need this:

```
+            if (recip) {
 +                result = 1.0f / result;
 +            }
```

Because the c `pow` function will handle negative exponents.

Also, this if case will never be reached:

```
+        if (typeof exp == "int32")
 +        {
 +            exp = $i32_to_f32(exp);
 +        }
```

Because it's inside a check for `typeof exp == 'float32'`. Should probably remove that check, because it is valid to have a float base with an integer power. Also note that it's also possible to have an integer base with a float power. We should also test all these combinations. See the `fp_assert` function in the tests.

**Comment by bigs** [comment]
haha i told myself it’d be clean but this is what i get for doing work on breaks at the job. ya i’ll have some time in a bit and will finish it up

**Pull request merged**
