### PR TITLE
Escape Function Added

### PR DESCRIPTION
**Pull request by Tushark21**
Escape Function in c++.

### CODE REVIEW

**Comment by maximecb** [comment]
This isn't really what's needed. Sorry.

**Comment by Tushark21** [comment]
can you explain it in little more details

**Comment by maximecb** [comment]
The escape function should be implemented in Plush, and should reflect the implementation of the `escapeStr` function found in `vm/serialize.cpp`.

**Comment by Tushark21** [comment]
Sorry, I don't know about this Implementation.

**Pull request closed without merging**
