### PR TITLE
Quicksort for arrays

### PR DESCRIPTION
**Pull request by jammln**
Sorry about the messed up commits. This passes a simple test but should work with any array. Not got around to benchmarking.

### CODE REVIEW

**Comment by maximecb** [comment]
Nitpick: curly braces should go on their own line

In terms of testing, I would like to see corner cases like a zero and one-element array being tested.

**Comment by jammln** [comment]
I should really make a check list before submitting a pull request. The conflict issue is quite confusing as I have never encountered it before? Any suggestions to fix it?

**Comment by krypt-n** [comment]
E.g. a66fb8feedc16a587b64b5a3c718ad60bdafddf2 made changes to arrays.pls that are not present in the branch you are working on. Depending on how used to these things you are, I'd recommend rebasing your master branch to zetavm:master and force-pushing to your fork (that would produce a cleaner set of commits) or simply merging zetavm:master into your master.

**Comment by jammln** [comment]
Thanks for the help, I think I went about that in a very unorthodox way, hopefully next time I'll get it right.

**Comment by maximecb** [comment]
Good job :)

**Pull request merged**
