### PR TITLE
Espresso language implementation

### PR DESCRIPTION
**Pull request by Maaarcocr**
This is a very first version of my language. It has similarities with Plush, but I will add more features in the future that will make them a bit more different. 

The front-end of the language is written in Python. I consider this a very first and small step towards the creation of a python library that can help creating a language with ZetaVM bytecode. 

One interesting (and very small feature) that I added is the capability to run the interpreter with no runtime, which sometimes can be useful if you want to know how a particular piece of code is translated.

### CODE REVIEW

**Comment by maximecb** [comment]
It does look similar to Plush, but it is good that we have a Python implementation now.

> One interesting (and very small feature) that I added is the capability to run the interpreter with no runtime

How would you use that?

**Comment by Maaarcocr** [comment]
> How would you use that?

```python espresso/main.py noruntime "file_name"```

I just noticed that I commented out the print statement for this feature, thus it would result in no input. I'm making another PR to fix this.

**Comment by maximecb** [comment]
Thanks for getting this done in time for PolyConf :)

One thing I would like to see, if you have time, is more tests, with asserts. When you have few automated tests, it's easy to break something without realizing it, especially in a compiler.

**Comment by Maaarcocr** [comment]
I'll write tests as soon as possible!

**Pull request merged**
