### PR TITLE
Added Initial Implementation of command line argument parser

### PR DESCRIPTION
**Pull request by ashwanidausodia**
Based on the discussion on #55, I've implemented initial version of basic argument parser. Have a look and tell me if any improvements are needed.

### CODE REVIEW

**Comment by maximecb** [comment]
You are very fast!

My feedback would be:

- I think we should actually use the term options instead of arguments, to avoid any confusion with function arguments in the VM. So `UIntOpt`, `BoolOpt`, `OptParser`.

- Why do we need both a builder and parser class? Would be simpler if we could just do `OptParser.add(opt)`

- One thing I still don't love about the current design is that adding a new option will likely require adding it in three places. We have to instantiate the object in a cpp file, declare it in a header so it's accessible to other cpp files, and we have to add it to the parser/builder. I realize there might be no convenient way to fix this in C++, and we may just have to live with this limitation.

**Comment by ashwanidausodia** [comment]
First two points, I have taken care of. For third point, I did not get why declaration and initialization has to be at two different places.

**Comment by maximecb** [comment]
> First two points, I have taken care of. For third point, I did not get why declaration and initialization has to be at two different places.

Because the practical use case is that say, the JIT compiler will need to read the enable_jit option, so it has to be declared in some header somewhere... But it doesn't matter that much, we can have extern declarations in an `options.h` file.

Are you able to determine why one of the travis builds is failing?

**Comment by ashwanidausodia** [comment]
On my machine it is failing even on master branch. It is in espresso. It thows some exception when it tries to generate the zeta image from `test.espr`. It is the last line of `run_test.sh`. I think it is not related to my changes

**Comment by maximecb** [comment]
I just pushed a commit and it passes all the tests. Can you copy and paste the error output you're getting?

**Comment by ashwanidausodia** [comment]
On my machine it was failing because I am using arch_linux which defaults to python3. If I change the command to python2 in `espresso.sh`, it works. Anyway I have taken your changes. Lets see if it passes

**Comment by ashwanidausodia** [comment]
It was my mistake. In a test case, I set argc=3 and argv had only two values. It was a copy paste error because other testcase had argc=3. It caused segmenation fault when parser tried to access the third arg. I've fixed it, now it's passing.

**Pull request merged**
