### PR TITLE
Random Number Generation package

### PR DESCRIPTION
**Pull request by tommyettinger**
The code should be in the right place, but I don't know if the API is exactly how it should be. On top of the methods mentioned in #39 's code sample, I have added the two "bonus"  methods you mentioned, `boolean()` to get a random bool and `select()` to get a random item from an array, plus `setState()` to reseed the state on an existing generator. The methods use `:` during a call right now because I'm not sure how to distinguish that from a class that uses`.`, and I need to change the state of the RNG during number generation. I think the style of object creation might not be the best way for the final version, but it could be acceptable. I have not yet written a benchmark because I wanted some feedback on whether the API should change. Speed seems fine so far (I generate 1000 random numbers from a pair of identical generators and compare them in a test; it seems to have less performance impact than printing text), but I'm not sure how I should be testing performance.

### CODE REVIEW

**Comment by maximecb** [comment]
Seems pretty great overall. Well-done. I think the object syntax is fine. It has the advantage that we can have multiple RNGs of different types, and potentially serialize them.

Some comments:
- Don't export `randomize`
- I would rename `select` to `choice` to match the Python method name
- Rename `setState` to `seed` because that seems more conventional in terms of naming.

I [added a benchmark](https://github.com/zetavm/zetavm/commit/35fc6f5375c1e25ed345ecbae84780d20ad481d1) of rng:float(), because this is the part I'm most interested in. On my system it takes about 3700ms to generate 1M numbers. It would take about 168ms to generate 1 second of noise at 44100Hz. For that kind of application, a smaller state would make sense.

**Comment by tommyettinger** [comment]
I did some benchmarks of my own, and it's surprising how little effect the state size actually has on speed. I tested a large number of calls of the random package's randomize() function vs. the same number of calls to rng:fullInt(), both producing the full range of ints, and the times are almost identical; I believe rng:fullInt() was slightly faster. The state of randomize() is just one int, not even in an array; compare this to the 65-element array of int32 that the RNG object uses. In the larger RNG, though, only two elements of state are updated to produce each random number (a third is read but not changed), so the large state size isn't much different from a generator with 3 or 4 ints in an array.

I think randomize() should be exported simply as a tool to get pseudo-random numbers without constructing an RNG, such as for test data that should be different with each iteration. I find myself using similar methods almost as often as the RNGs themselves in my Java code, though in the Java case that saves an object allocation and may be beneficial for performance. Because randomize() uses a different algorithm than the main one for fullInt() and such, it can also be useful for trying out a different sequence of numbers (or sequences of numbers, depending on how the input is updated) in tandem with an RNG, or for further altering an RNG's results.

I agree on naming for both select -> choice and setState -> seed. Well, I'd call setState "reseed", because it specifically does not initialize the state to a 65-element array, and seed is already used as an expected name for the seed value. It also points out that you can't use reseed to make some new RNG, and must already have an RNG.

If speed is critical here, this should probably be written in C++ and somehow accessed by FFI or some equivalent. Until Zeta can compile to machine code, it won't be reasonable to compare it to things that do compile to machine code. Just as a note of how unreasonable this would be, the random package's fullInt() function is currently about 1000x to 1300x slower than similar Java code, since it takes the same amount of time or more to produce 1/1000 as many generated values. There are so many things that could account for that amount of slowdown that there's no point in trying them all, though the interpreter can of course still be optimized.

Back to the code we have! On my laptop (with an i7-6700HQ processor and DDR4 RAM), running this code:

```
#language "lang/plush/0"
var random = import "std/random/0";
var rng = random.globalRNG;
var test = function ()
{
    for (var i = 0; i < 1000000; i += 1)
    {
        rng:float(-1.0f, 1.0f);
    }
    return i;
};
test();
```

Takes this much time in the benchmark, compiled with `./configure --enable-ndebug`:
```
random_float_1m.pls       2882 ms
```

I'll take a look at your benchmark and try to see what could result in a slower time. I did notice in my code that directly using globalRNG without first storing it as a local var caused some amount of slowdown. I also noticed that writing `-1f` is apparently not how I should have done it, because various syntax errors happened when I tried that.

**Comment by maximecb** [comment]
I would avoid having a global RNG, because it's not really any simpler than just instantiating one.

**Comment by maximecb** [comment]
Looked at the source code of your package a bit more. Lots of function calls. Zeta is really going to need inlining in order to perform well.

**Comment by tommyettinger** [comment]
I have a version with hand-inlined code for most of the RNG functions, and it does make a difference. Timing looks like:

```
benchmarks/random_int_1m.pls         1871 ms
benchmarks/random_float_1m.pls       2246 ms
```

Where without inlining, it looks like:

```
benchmarks/random_int_1m.pls         2095 ms
benchmarks/random_float_1m.pls       2426 ms
```

The last benchmark (which took 2426 ms) probably wasn't testing the same method; I think it was testing smallFloat() instead of float(), and so was doing less work. I think in most of the non-inlined tests, the million floats took longer than 2426 ms with the correct function.

Trying alternatives for how I store the temporary variable in fullInt() doesn't seem to provide any benefit.
During inlining, I found a way to speed up float generation somewhat; it's just masking the generated 32-bit value with `&` instead of shifting with `>>>`, but that tends to be a little faster. It does produce different results. I can send the results in another PR if you want the somewhat-ugly/repetitive hand-inlined code in the ZetaVM repo. I'll need to remove any changes of mine that conflict, and there may be a few.

**Comment by maximecb** [comment]
I think I would prefer we keep the more maintainable (not hand inlined) code. Zeta needs to perform more optimizations anyway.

Speaking of which, I just pushed something which should give you a free speedup of 5-10% :)

**Pull request merged**
