### PR TITLE
String Interning implementation

### PR DESCRIPTION
**Pull request by Maaarcocr**
I implemented string interning in zeta. In order to accomplish this I used an unordered_map, but the code is relatively modular, so changing the internal implementation of the StringPool shouldn't be too difficult. (The StringPool is the class that takes care of managing strings).

I've done the benchmarks on my machine and they seem quite good!

Before:
```
benchmarks/img_fill.pls               337 ms
benchmarks/incr_field_1m.pls          641 ms
benchmarks/fcalls_10m.zim             885 ms
benchmarks/fib29.pls                  699 ms
benchmarks/loop_cnt_100m.zim         4110 ms
benchmarks/plush_parser.zim           320 ms
benchmarks/saw_wave.pls               770 ms
benchmarks/sine_wave.pls              873 ms
--------------------------------------------
geometric mean                        766 ms
``` 

After: 
```
benchmarks/img_fill.pls               282 ms
benchmarks/incr_field_1m.pls          648 ms
benchmarks/fcalls_10m.zim             929 ms
benchmarks/fib29.pls                  658 ms
benchmarks/loop_cnt_100m.zim         4299 ms
benchmarks/plush_parser.zim           203 ms
benchmarks/saw_wave.pls               614 ms
benchmarks/sine_wave.pls              781 ms
--------------------------------------------
geometric mean                        682 ms
```

The plush_parser got a nice boost!

### CODE REVIEW

**Comment by krypt-n** [comment]
Could you add a comment with a reference for the hash function?

**Comment by Maaarcocr** [comment]
@krypt-n thanks for spotting that out! I was supposed to put it in first place, but I forgot.

**Comment by tommyettinger** [comment]
There seems to be some amount of overhead added, maybe per-call or per-loop-iteration, since the benchmarks are mostly faster except for the cases where millions of statements are run, where it seems to be that there's a slight regression. That's kinda surprising, since I don't think `loop_cnt_100m.zim` does much with strings... I haven't looked over the code yet, but does anyone have ideas why this sometimes hinders performance instead of helping it?

**Comment by maximecb** [comment]
@tommyettinger loop_cnt_100m is handwritten bytecode, it only has comparisons, branching, incrementing a loop counter. It uses no strings, no objects, no function calls. It's basically a metric of how fast the interpreter loop runs.

@maaarcocr Nicely done. Makes sense that plush_parser got the biggest win since it does so much string manipulation. Have to wonder if we could speed up other string ops in a useful way.

Some comments/nitpicks:

hashFunction => you should call the function murmurHash3 or whatever version it is.

class StringHasher => you should probably make this private within the StringPool class.

nitpick: I would rename addNewString to just newString.

**Comment by Maaarcocr** [comment]
@tommyettinger I think the benchmarks, especially the one for the loops, can have some sort of noise due to the state of RAM and CPU of the computer. I ran the benchmark again and I got a better result than both of my previous benchmarks. 

@maximecb I will have a look to see if we can have other speed-ups in other ops. 

I will rename and move the class as soon as I have time!

**Comment by tommyettinger** [comment]
Whew, glad to hear that issue is probably just background noise. Like @maximecb , I also wonder if other string operations might be able to benefit from this or other optimizations.

**Comment by Maaarcocr** [comment]
@maximecb I have done what you asked. 

One trade-off that we could try is to cache the value of this operator: https://github.com/zetavm/zetavm/blob/master/vm/runtime.cpp#L171

This value is probably calculate multiple times for the same string. Apart from this, I'm not really sure if we can do anything else.

**Comment by maximecb** [comment]
Thanks Marco :)

I don't think it makes sense to cache that operator, since it only gets a pointer to the string data, which is not an expensive operation. To cache the value and retrieve it from somewhere would be just as expensive as computing it.

I was thinking we could possibly speed up string concatenation. Right now, string concat is going to allocate a new string object, copy over the new strings, then look that up into the hash table to look for a match. Possibly, we could use compute the hash value of the concatenated string and do a lookup without allocating the intermediate string object.

Before getting into that though, it would make sense to check how much string concatenation we're actually doing. Another first step we could take is to avoid allocating an std::string object to do the concatenation, or to use alloca if it makes sense to do that.

**Pull request merged**
