### PR TITLE
Implement recursive string.join function

### PR DESCRIPTION
**Pull request by bigs**
Addresses #105, implementing a recursive, divide and conquer algorithm.

### Notes

This change introduces a dependency on the `array` library. Not sure if that's acceptable and am happy to change it if not. Also generally not super familiar on style beyond what's documented in the contribution guidelines. Is the level of expression nesting OK? Should I go further?

Happy to make any amendments per project goals and hope this is the first change of many!

*Edit: Worthy of note is the fact that the existing test still passes. Happy to add additional tests for lists of length zero and one.*

*Double edit: Are we concerned about stack growth?*

### CODE REVIEW

**Comment by maximecb** [comment]
> This change introduces a dependency on the array library. Not sure if that's acceptable and am happy to change it if not.

Hmmm. The problem is that slice is going to copy the array contents. I think you should avoid using the array functions. Should probably make a helper function and pass indices into the array. Can use the `+` operator to concatenate two arrays.

> Happy to add additional tests for lists of length zero and one.

That seems like a good idea.

**Comment by bigs** [comment]
> Should probably make a helper function and pass indices into the array. Can use the + operator to concatenate two arrays.

interesting! on it!

> That seems like a good idea.

and this as well :)

**Comment by bigs** [comment]
@maximecb added a few test cases and reimplemented the algorithm as we discussed. one thing i couldn't figure out was how to do recursion with my helper function, so i wound up passing it a reference to itself. definitely understand if this is not preferred style, but i couldn't find any documentation otherwise. what do you think? is there another approach you'd prefer? if recursion is otherwise a no-no i can implement a stack based approach.

**Comment by maximecb** [comment]
Recursion is fine IMO, because it will only be log(n) deep.

The code seems good, but I would move `joinSub` into the global scope, to avoid creating a closure every time `join` is called.

**Comment by bigs** [comment]
@maximecb updated!

**Comment by maximecb** [comment]
Well done :)

**Comment by bigs** [comment]
hah, after threatening to contribute, it's finally happened! on to the next project.

**Pull request merged**
